# Docker con aprovisionamiento a través de shell IMPERATIVO
# Vagrant.configure("2") do |config|
#   config.vm.box = "uwbbi/bionic-arm64"
#   config.vm.provision "shell",
#     inline: "
#     sudo apt install docker
#     sudo snap install docker
#     sudo docker pull hello-world
#     sudo docker run hello-world
#     "
# end

# Docker aprovisionamiento a través de ansible DECLARATIVO
Vagrant.configure("2") do |config|
  config.vm.box = "uwbbi/bionic-arm64"
  config.vm.provision "ansible" do |ansible|
  ansible.playbook = "playbook.yml"
  end
end 